image: node:20

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

pages:
  stage: deploy
  script:
    - npm ci
    - PUBLIC_URL="https://${CI_PROJECT_NAMESPACE}.gitlab.io/${CI_PROJECT_NAME}" npm run build
    - mv build public
  artifacts:
    paths:
      - public
  only:
    - main
